# Generated by Django 2.1 on 2021-04-26 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(default=datetime.datetime(2021, 4, 26, 18, 19, 3, 961507, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
